[entryPoints]
  [entryPoints.http]
     address = ":80"
    [entryPoints.http.redirect]
        regex="/member"
        replacement="/v2/users"
        permanent=true
  [entryPoints.https]
     address = ":443"
    [entryPoints.https.tls]

[api]

[file]
  filename="/etc/traefik/rules.toml"
  watch=true

[consulCatalog]
endpoint = "172.16.17.158:8500"
exposedByDefault=true
domain="shenyi.com"
frontEndRule="Host:{{.ServiceName}}. {{.Domain}}"
strictChecks=true